### ISSUE TITLE
Scrobbles upcoming songs

### ISSUE THREAD

**Issue by cheshire137** [cheshire137/soma-chrome#10]
I was listening to PopTron just now. It scrobbled AlunaGeorge's You Know You Like It while Capital Cities' Safe and Sound was still playing. Then You Know You Like It started playing. So it wasn't a lie, both songs were played, it's just the scrobbles were a little premature.

Maybe this is the DJs updating their 'now playing' info in advance. Should the extension delay scrobbling? Should it keep track of the current and previous played track and scrobble the previous track on track change?

**Comment by rustyhodge** [comment]
This issue is caused by the different buffer amounts on some of our streamservers.

Buffers can be over 2 minutes currently (on the ice.somafm.com server pool; the shoutcast servers have 20-30 second buffers), we may change that in the future and we're also going to phase out the shoutcast servers and use Icecast only. The metadata within the stream is sync'ed to the buffers thought. The XML feed gets updated as we play songs, so due to the buffering, it may seem like we're posting songs before we play them.

I'd suggest waiting 2-3 minutes after a song change to scrobble it.
